zhcet-amu/zhcet-web

- src/main/java/in/ac/amu/zhcet/data/DatabaseLoader.java
- src/main/java/in/ac/amu/zhcet/data/model/Course.java
- src/main/java/in/ac/amu/zhcet/data/model/Department.java
- src/main/java/in/ac/amu/zhcet/data/repository/DepartmentRepository.java
- Add department model
- Add department in course
> Department refactor

- src/main/java/in/ac/amu/zhcet/controller/department/CourseCreationController.java
- src/main/java/in/ac/amu/zhcet/data/CourseType.java
- src/main/java/in/ac/amu/zhcet/data/model/Course.java
- src/main/java/in/ac/amu/zhcet/service/core/DepartmentAdminService.java
- src/main/java/in/ac/amu/zhcet/service/core/FloatedCourseService.java
- src/main/java/in/ac/amu/zhcet/service/token/EmailVerificationService.java
- src/main/resources/db/migration/V2.0.6__add_description_course.sql
- src/main/resources/templates/dean/admin.html
- src/main/resources/templates/dean/configuration.html
- src/main/resources/templates/department/add_course.html
- src/main/resources/templates/department/admin.html
- src/main/resources/templates/fragments/layout.html
- src/main/resources/templates/fragments/navigation.html
- src/main/resources/templates/user/profile.html
Fixes #43 
- Add several endpoints for department
- Create course add form
- Add finer duplicate management
- Course add page status - WIP
> feat: Add create course page

- build.gradle
- src/main/java/in/ac/amu/zhcet/controller/dean/ConfigurationController.java
- src/main/java/in/ac/amu/zhcet/data/model/dto/Config.java
- src/main/java/in/ac/amu/zhcet/data/model/dto/mapper/ConfigurationMapper.java
- src/main/java/in/ac/amu/zhcet/service/core/CourseManagementService.java
- src/main/java/in/ac/amu/zhcet/service/core/DepartmentService.java
> feat: Add mapstruct for mapping objects

- src/main/java/in/ac/amu/zhcet/controller/department/CourseCreationController.java
- src/main/java/in/ac/amu/zhcet/controller/department/CoursesController.java
- src/main/java/in/ac/amu/zhcet/data/repository/CourseRepository.java
- src/main/java/in/ac/amu/zhcet/service/ViewService.java
- src/main/java/in/ac/amu/zhcet/service/core/CourseManagementService.java
- src/main/resources/static/css/styles.css
- src/main/resources/templates/department/courses.html
- src/main/resources/templates/fragments/navigation.html
> feat: Create courses page

- src/main/java/in/ac/amu/zhcet/controller/department/CourseCreationController.java
- src/main/java/in/ac/amu/zhcet/controller/department/CourseEditController.java
- src/main/java/in/ac/amu/zhcet/service/core/CourseManagementService.java
- src/main/java/in/ac/amu/zhcet/utils/UpdateException.java
- src/main/resources/templates/department/add_course.html
- src/main/resources/templates/department/courses.html
- src/main/resources/templates/department/edit_course.html
- src/main/resources/templates/department/fragments/course_form.html
> feat: Create course edit page

- src/main/java/in/ac/amu/zhcet/controller/department/CourseManagementController.java
- src/main/java/in/ac/amu/zhcet/controller/faculty/FloatedCourseController.java
- src/main/java/in/ac/amu/zhcet/utils/Utils.java
> feat: Sort attendance entries

- src/main/java/in/ac/amu/zhcet/controller/department/CoursesRestController.java
- src/main/java/in/ac/amu/zhcet/controller/department/FloatCourseController.java
- src/main/resources/static/css/styles.css
- src/main/resources/static/js/float-course.js
- src/main/resources/static/js/fuzzyhound.js
- src/main/resources/templates/department/courses.html
- src/main/resources/templates/department/float_course.html
- src/main/resources/templates/fragments/navigation.html
> feat: Add float course page

- src/main/java/in/ac/amu/zhcet/controller/department/FacultyRestController.java
- src/main/java/in/ac/amu/zhcet/controller/department/FloatCourseController.java
- src/main/java/in/ac/amu/zhcet/controller/department/FloatedCourseController.java
- src/main/java/in/ac/amu/zhcet/data/model/CourseInCharge.java
- src/main/java/in/ac/amu/zhcet/data/model/CourseRegistration.java
- src/main/java/in/ac/amu/zhcet/data/model/FacultyMember.java
- src/main/java/in/ac/amu/zhcet/data/model/FloatedCourse.java
- src/main/java/in/ac/amu/zhcet/data/repository/CourseInChargeRepository.java
- src/main/java/in/ac/amu/zhcet/data/repository/FacultyRepository.java
- src/main/java/in/ac/amu/zhcet/service/ViewService.java
- src/main/java/in/ac/amu/zhcet/service/core/CourseManagementService.java
- src/main/java/in/ac/amu/zhcet/service/core/FacultyService.java
- src/main/java/in/ac/amu/zhcet/utils/Utils.java
- src/main/resources/db/migration/V2.0.7__add_working_faculty_member.sql
- src/main/resources/db/migration/V2.0.8__modify_unique_in_charge.sql
- src/main/resources/static/css/floated-course.css
- src/main/resources/static/js/floated-course.js
- src/main/resources/templates/department/courses.html
- src/main/resources/templates/department/floated_course.html
- src/main/resources/templates/department/fragments/add_in_charge.html
- src/main/resources/templates/department/fragments/register_students.html
- src/main/resources/templates/department/fragments/registered_students.html
- src/main/resources/templates/department/fragments/unfloat_course.html
- src/main/resources/templates/fragments/layout.html
Fixes #55 Fixes #41 
- Add faculty REST controller
- Fix cascading properties of models
- Fix unique attribute of course in-charge
- Break floated course page in fragments
- Create avatar ViewService method
- Add working column to faculty member
- Modify course float and unfloat structure
> feat: Add course in charge

- src/main/resources/templates/department/admin.html
> feat: Add media panel to department admin

- src/main/java/in/ac/amu/zhcet/data/model/user/UserDetail.java
- src/main/java/in/ac/amu/zhcet/service/UserService.java
- src/main/resources/db/migration/V4.2.3__add_user_dob.sql
- src/main/resources/templates/user/fragments/profile_form.html
> feat: Add date of birth in User model

- src/main/resources/config/application.yaml
> fix: Explicit open-in-view for hibernate

- src/main/java/amu/zhcet/email/EmailConfiguration.java
> fix: Move optional autowired inside constructor

- src/main/java/amu/zhcet/core/admin/attendance/AttendanceDownloadService.java
- src/main/java/amu/zhcet/core/admin/attendance/AttendanceMapper.java
- src/main/java/amu/zhcet/core/admin/faculty/attendance/upload/AttendanceUploadController.java
- src/main/resources/static/css/attendance-upload.css
- src/main/resources/static/js/attendance-upload.js
- src/main/resources/templates/faculty/course_attendance.html
- src/main/resources/templates/faculty/fragments/attendance.html
- src/main/resources/templates/faculty/fragments/attendance_confirm.html
- Make attendance editor smart
- Add delivered check
- Add delivered equalizer
> feat: Allow to edit attendance directly

- circle.yml
- src/main/java/amu/zhcet/auth/password/reset/PasswordResetService.java
- src/main/java/amu/zhcet/auth/password/reset/ResetTokenSender.java
- src/main/java/amu/zhcet/core/admin/dean/registration/faculty/FacultyRegistrationAdapter.java
- src/main/java/amu/zhcet/core/profile/EmailUnsubscribeController.java
- src/main/java/amu/zhcet/email/LinkMailService.java
- src/main/java/amu/zhcet/security/CryptoUtils.java
- src/main/java/amu/zhcet/security/SecureProperties.java
- src/main/java/amu/zhcet/security/SecurePropertyConfig.java
- src/main/java/amu/zhcet/security/SecurityUtils.java
- src/test/java/amu/zhcet/common/utils/SecurityUtilsTest.java
- src/test/java/amu/zhcet/security/CryptoUtilsTest.java
- Add encryption related methods
- Add encryption method versioning
- Add tests for add encryption branches
> refactor: Split SecurityUtils into CryptoUtils

- build.gradle
- src/main/resources/templates/dean/fragments/user_table.html
fixes #138 
As of now I am displaying date and time in two different columns. It can be made prettier with `DateTimeFormatter`. For that, either I have to add a new field in `BaseEntity`model which returns a formatted date and time or pass the `DateTimeFormatter` object in the view itself and format the date there. Which will be better ?
> fix: improve date display in dean/admin

- src/main/java/amu/zhcet/auth/UserAuth.java
- src/main/java/amu/zhcet/auth/twofactor/TwoFAService.java
> feat: Encrypt the TOTP before storing in DB

- src/main/resources/static/js/float-course.js
- src/main/resources/templates/department/float_course.html
> ui: Add proper margins in Float Course section

- src/main/resources/static/css/styles.css
- src/main/resources/templates/department/fragments/course_form.html
- src/main/resources/templates/management/edit_notification.html
- src/main/resources/templates/user/fragments/account.html
- src/main/resources/templates/user/fragments/account_email.html
> ui: Align material icons in forms to middle

- src/main/resources/templates/fragments/scripts.html
> chore: Add MUI js

- src/main/resources/static/css/styles.css
> ui: Make red bg elements text white

- src/main/resources/templates/faculty/fragments/attendance_download.html
> ui: Remove blue patch from attendance download card

- src/main/resources/templates/department/float_course.html
> ui: Make semester tags float to right

- src/main/resources/static/css/styles.css
- src/main/resources/templates/fragments/toolbar.html
> fix(ui): Add alert icons

- src/main/resources/templates/user/2fa_enable.html
> Replace fieldset with div

- src/main/java/amu/zhcet/auth/verification/DuplicateEmailException.java
- src/main/java/amu/zhcet/auth/verification/EmailVerificationController.java
- src/main/java/amu/zhcet/auth/verification/EmailVerificationService.java
- src/main/java/amu/zhcet/auth/verification/RecentVerificationException.java
- src/main/java/amu/zhcet/auth/verification/TokenVerificationException.java
- src/test/java/amu/zhcet/auth/verification/DuplicateEmailExceptionTest.java
- src/test/java/amu/zhcet/auth/verification/RecentVerificationExceptionTest.java
> fix: Handle specific exceptions while email verification

- src/main/java/amu/zhcet/core/admin/dean/rolemanagement/RoleManagementController.java
> fix: Remove VERIFIED_USER role from admin panel

- src/main/resources/config/application.yaml
> Change session ID name to ZHCET_SESSION_ID

- CHANGELOG.md
- src/main/java/amu/zhcet/CoreApplication.java
- Add workaround for issue https://github.com/spring-projects/spring-boot/issues/14897
> fix: Resource versioning content strategy

- .gitignore
- package.json
- rollup.config.js
- src/main/resources/src/app.mjs
- yarn.lock
Fix JS generation for Intelij IDEA
> fix: Idea JS generation

- src/main/java/amu/zhcet/auth/UserDetailService.java
> fix: Recreate user auth when changing permissions
